# Generated by Django 3.2.13 on 2022-06-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alertapersona',
            fields=[
                ('id_alerta', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre_paler', models.CharField(blank=True, max_length=200, null=True)),
                ('motivo_aler', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'alertapersona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alertavehiculo',
            fields=[
                ('id_alerv', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('placa_a', models.CharField(blank=True, max_length=10, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'alertavehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Motivodeviaje',
            fields=[
                ('id_motivo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('motivoviaje', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'motivodeviaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('paisesn', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('dui', models.CharField(blank=True, max_length=10, null=True)),
                ('pasaporte', models.CharField(blank=True, max_length=13, null=True)),
                ('visa', models.CharField(blank=True, max_length=256, null=True)),
                ('fechaentrada', models.DateField(blank=True, null=True)),
                ('fechasalida', models.DateField(blank=True, null=True)),
                ('nombre_padre', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_madre', models.CharField(blank=True, max_length=200, null=True)),
                ('nombretutor', models.CharField(blank=True, max_length=200, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('rol', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('contra', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehi', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
    ]
